### PR TITLE
API&Organisation Rework

### PR DESCRIPTION
**Pull request by Kermer**
How about this @Gramps ? #5

### CODE REVIEW

**Comment by Gramps** [comment]
Damn, dude, that's very pretty!  That is a great commit. Looks like you added in all the core functions and really cleaned up the code.  I will dig into it this Thursday after my update goes live.  I'd really like to use a lot of the features you implemented and I didn't for a near-future game.

Also, I was told that the Mac hooks I put in do work for Mac.  I was never able to test them but was told they are indeed functional.  You can put those in there as well.  However, I still have them listed as experimental as the person did not have a game to test them on.

Again, that is some class A work, sir!

**Comment by Gramps** [comment]
I will also probably do a pull on this and start adding in more Steamworks functions.  However, I probably won't start that until after the 31st as my game launches on Steam that day!

**Comment by Kermer** [comment]
That's actually good. I'll add more of those simple functions (like DLCs checking) in next days.
After that maybe you'll be able to carry this one on and I'll focus on more complicated stuff like Workshop and Servers/Lobbies/Matchmaking.

**Comment by Gramps** [comment]
Probably wise as you are clearly better versed at C++.  I do have some DLC checks in there but there is still a wealth of additional functionality to add.

**Pull request merged**
